{{- if .Values.awsCredentials.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "object-detection-api.fullname" . }}-aws-credentials
  labels:
    {{- include "object-detection-api.labels" . | nindent 4 }}
type: Opaque
data:
  accessKeyId: {{ .Values.awsCredentials.accessKeyId | b64enc }}
  secretAccessKey: {{ .Values.awsCredentials.secretAccessKey | b64enc }}
{{- end }}
---
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "object-detection-api.fullname" . }}-secret
  labels:
    {{- include "object-detection-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }} 